image: node:16

stages:
  - test
  - deploy

before_script:
  - yarn

cache:
  paths:
    - node_modules/
    - .next/

lint:
  stage: test
  script:
    - yarn lint

build:
  stage: test
  script:
    - yarn export
  artifacts:
    paths:
      - out

pages:
  stage: deploy
  script: cp -rf out/* public
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - main
